### PR TITLE
Add bandwidth logic

### PR DESCRIPTION
**Pull request by megoRU**
1. According to the documentation, you need to send it to Bytes, which is exactly what we send. But I didn't quite understand whether to add it correctly: `download` & `upload`

### CODE REVIEW

**Comment by pvhil** [comment]
Tried this on my PC and Heroku. `.get(0)` will often use the wrong NetworkIF. On the new development branch I am getting the right one with the help of a for loop but im not sure if this is best practice. Heres the link to the branch: https://github.com/pvhil/unofficial-statcord-wrapper/tree/development

**Comment by megoRU** [comment]
It should be better now. Or not :)

**Comment by pvhil** [comment]
This throws me `java.lang.AbstractMethodError`. I will have a look again in the next days.

`Exception in thread "main" java.lang.AbstractMethodError: Receiver class com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX does not define or inherit an implementation of the resolved method abstract getFieldOrder()Ljava/util/List; of abstract class com.sun.jna.Structure.
	at com.sun.jna.Structure.fieldOrder(Structure.java:952)
	at com.sun.jna.Structure.getFields(Structure.java:1006)
	at com.sun.jna.Structure.deriveLayout(Structure.java:1172)
	at com.sun.jna.Structure.calculateSize(Structure.java:1097)
	at com.sun.jna.Structure.calculateSize(Structure.java:1049)
	at com.sun.jna.Structure.allocateMemory(Structure.java:403)
	at com.sun.jna.Structure.<init>(Structure.java:194)
	at com.sun.jna.Structure.<init>(Structure.java:182)
	at com.sun.jna.Structure.<init>(Structure.java:169)
	at com.sun.jna.Structure.<init>(Structure.java:161)
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1968)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127)
	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:107)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:147)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:141)
	at Statcord.getNetworkName(Statcord.java:258)
	at Statcord.start(Statcord.java:62)
	at main.main(main.java:26) // ignore
`

**Comment by megoRU** [comment]
Is it on Heroku throwing an exception*?

**Comment by pvhil** [comment]
No on my pc. Looked it up on google, tried to add JNA as a dependency and tried to rearrange dependencies. Still throwing.

**Comment by megoRU** [comment]
I don't throw exceptions. Maybe you have something wrong, but what...

**Comment by pvhil** [comment]
Yeah I will look into it the next days. But Thanks!

**Pull request closed without merging**
